language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - iojs-v1
  - iojs-v2
script: npm test
before_script:
  - npm install
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
env:
  global:
    - secure: SdTY/h7ShhBaYhvPrBD26iV1tF1OB+Co2SD2VadFjl8aL22SZtpnABWI0Xvi1beiwpXtypkC2k8Y4fZnqZseLjHv1TFv4IjSpucnPyiLz4VWy1Ndi20NhXOKhCBm/04YeSlx5Y4jPrIx6ZilH2SDkSJREEoex6Zscz7eP7NWrKd1nVhWUp4Bks8iV63FweuKe62dpte7p6nf4uVdCl23voSeq/MWfy042hOwLtFtn+h6dgTsBPa7Ae7C/LFRNHjC34TWzIPPDHghCe8kVXnKBvFBGXz9AyWtr3+LCyPRf9Ca3HddzH5c9usZc+9yoUNlCxDiH1KZb+tg/kDFlcDxlbYapJRcXtQZTCo4MYi/xQLP38zFMMU3NVkROl07aAbB8mlayv4hzyUrjpICyK9uoDkS+OCLtVwdp+1gcHyJPl87m5Cf+R5tON/ufA9irHwSfeLMT+YVbV2ncKwTA8k6yti9HCV91d5jS9Uqz/ypozUurHsPbuWINm4KuWcCezQX5u4Vm9aiIrX7rNavmW738YRhBFJeFQmkLqrK8oIIhkyHARxLLVO2LSiUDgYE7nUOaOq3nn5yUPLDD2fpWCiMZO7g6D8hB/DgS2eZlw75mo2IX0r1HYTWZIspP0p7TBm9s95L9w8W430l1p30Q3WOzddFrnAzRpX8Grs0M1CluJo=
    - secure: B9aiEHYlTzJRUGmckGtYoxHa6mcRtLasTCrqPotFaq31iTjZ8CkyfWMj23RrAgaelzeIW8WPahsJgsmu3ZWaVpmAMfFVgWZdC8mkhgUPfhTCmi7qGfz1u94J3wGPLUb9aGwECRiL4hBeUT0Q1Xd34EIYLM/hwi3JJsI0nmaHyTzwQIXEquHfBVq4o55OtqHWkJPZW5eT8V6JSGCq73e8oBmjx3tLbIJB8rWyFZd1ata8/IHYsZnlgHHyeml0Sw1KurHO8+tzQgqS+RRSIp258JCJUKLqKFioYXq66QyfabGDM3ZQe1lo72ArGs1CJaCNec3orlODQhd9u+/xlCeebBocG/0xWSDBDlsIUyxJZM1HNDVtr9F2yceRgFOl/Lrxevxo7gA+c4fjqyhSw4IsrZO6cd4sXQ0SUzDZOZ8dVYG2jqpRXB5FaBgjmTBAsQnv5045ssvRw2y7dYlTPjn/wr7d3gCj5rI27R1HTlQKKp3skR0WEHPfZAalzFqIRUMYaDbXN7629fBkGz6Zl1j4v/ahtU9dMf1O4L1bDQwW0NQ4Ta2DXrNKb5pte1RGfyo6Z8HHdphxv5PES3AD+nznTq5y0S2TwPXOndvCr8d5MYRYjJ9zMUtOi0+mrq3dmYG29Nnd2QsBC5KZyHfx3hwNq2SxGQmcyO8eWFcMxzWUbUA=
